<?php
// $Id$

/**
 * @file
 * RESTful web services module.
 */

/**
 * Returns info about all defined resources.
 */
function restws_get_resource_info() {
  $info = &drupal_static(__FUNCTION__);
  if (!isset($info)) {
    $info = module_invoke_all('restws_resource_info');
    drupal_alter('restws_resource_info', $info);
  }
  return $info;
}

/**
 * Returns info about all defined formats.
 */
function restws_get_format_info() {
  $info = &drupal_static(__FUNCTION__);
  if (!isset($info)) {
    $info = module_invoke_all('restws_format_info');
    drupal_alter('restws_format_info', $info);
  }
  return $info;
}

/**
 * Implements hook_restws_resource_info().
 *
 * Provides resources for all entity types.
 */
function restws_restws_resource_info() {
  foreach (entity_get_info() as $entity_type => $info) {
    $result[$entity_type] = array(
      'label' => $info['label'],
      'class' => 'RestWSEntityResourceController',
    );
  }
  return $result;
}

/**
 * Returns a instance of a resource controller.
 *
 * @return RestWSResourceControllerInterface
 */
function restws_resource_controller($name) {
  $static = &drupal_static(__FUNCTION__);
  if (!isset($static[$name])) {
    $info = restws_restws_resource_info();
    $static[$name] = isset($info[$name]) ? new $info[$name]['class']($name, $info[$name]) : FALSE;
  }
  return $static[$name];
}

/**
 * Implements hook_restws_format_info().
 *
 * Provides basic formats.
 */
function restws_restws_format_info() {
  return array(
    'json' => array(
      'label' => t('JSON'),
      'class' => 'RestWSFormatJSON',
      'mime type' => 'application/json',
    ),
  );
}

/**
 * Returns an instance of a format.
 *
 * @return RestWSFormatInterface
 */
function restws_format($name) {
  $static = &drupal_static(__FUNCTION__);
  if (!isset($static[$name])) {
    $info = restws_get_format_info();
    $static[$name] = isset($info[$name]) ? new $info[$name]['class']($name, $info[$name]) : FALSE;
  }
  return $static[$name];
}

/**
 * Handles a request.
 *
 * @param $op
 *   One of 'create', 'update', 'delete' or 'view'.
 */
function restws_handle_request($op, $format, $resource, $id = NULL, $payload = NULL) {
  if (($resource_controller = restws_resource_controller($resource)) && $resource_controller->access($op, $id)) {
    try {
      $method = $op . 'Resource';
      if ($op == 'create') {
        print $format->$method($resource_controller, $payload);
        drupal_add_http_header('Status', '201 Created');
      }
      else {
        print $format->$method($resource_controller, $id, $payload);
      }
      drupal_add_http_header('Content-Type', $format->mimeType());
    }
    catch (RestWSException $e) {
      echo check_plain($e->getHTTPError());
      drupal_add_http_header('Status', $e->getHTTPError());
    }
  }
  else {
    echo '403 Forbidden';
    drupal_add_http_header('Status', '403 Forbidden');
    watchdog('access denied', check_plain($_GET['q']), NULL, WATCHDOG_WARNING);
  }
  drupal_page_footer();
  exit;
}

/**
 * An exception defining the HTTP error code and message.
 */
class RestWSException extends Exception {

  public function getHTTPError() {
    return '500 Internal Server Error';
  }
}

/**
 * Implements hook_menu_alter().
 */
function restws_menu_alter(&$items) {
  foreach (restws_get_resource_info() as $resource => $info) {
    // @todo document 'menu path'
    $menu_path = isset($info['menu_path']) ? $info['menu_path'] : $resource . '/%' . $resource;
    if (isset($items[$menu_path])) {
      // Preprend the page callback and the resource to the page arguments.
      array_unshift($items[$menu_path]['page arguments'], $resource, $items[$menu_path]['page callback']);
      $items[$menu_path]['page callback'] = 'restws_page_callback';
    }
    else {
      $menu_path = isset($info['menu_path']) ? $info['menu_path'] : $resource . '/%';
      $items[$menu_path] = array(
        'page callback' => 'restws_page_callback',
        'page arguments' => array($resource),
        'access callback' => TRUE,
      );
    }
    // Resource base path (e.g. /node or /user) for creating resources.
    // @todo fix 'menu path'
    if (!isset($info['menu_path'])) {
      if (isset($items[$resource])) {
        // Preprend the page callback and the resource to the page arguments.
        if (!isset($items[$resource]['page arguments'])) {
          $items[$resource]['page arguments'] = array();
        }
        array_unshift($items[$resource]['page arguments'], $resource, $items[$resource]['page callback']);
        $items[$resource]['page callback'] = 'restws_page_callback';
      }
      else {
        $items[$resource] = array(
          'page callback' => 'restws_page_callback',
          'page arguments' => array($resource),
          'access callback' => TRUE,
        );
      }
    }
  }
}

/**
 * Menu page callback.
 */
function restws_page_callback($resource, $page_callback = NULL) {
  $id_arg = arg(1);
  $format = FALSE;
  // Check for a appended .format string.
  if (($pos = strpos($id_arg, '.')) && $format_name = substr($id_arg, $pos + 1)) {
    $id = substr($id_arg, 0, $pos);
    $format = restws_format($format_name);
  }
  else {
    // Get format MIME type form HTTP Accept header
    $parts = explode(',', $_SERVER['HTTP_ACCEPT']);
    $format_mime = $parts[0];
    // White list for standard HTML browser requests.
    if (!in_array($format_mime, array('text/html', 'application/xhtml+xml'))) {
      $format = restws_format_mimetype($format_mime);
      $id = $id_arg;
    }
  }
  if ($format) {
    switch ($_SERVER['REQUEST_METHOD']) {
      case 'PUT':
        $op = 'create';
        break;
      case 'POST':
        $op = 'update';
        break;
      case 'DELETE':
        $op = 'delete';
        break;
      default:
        $op = 'view';
    }
    $payload = file_get_contents('php://input');
    restws_handle_request($op, $format, $resource, $id, $payload);
  }

  // @todo: Determine human readable URIs and redirect, if there is no
  // page callback.
  if (isset($page_callback)) {
    // Further page callback arguments have been appended to our arguments.
    $args = func_get_args();
    return call_user_func_array($page_callback, array_slice($args, 2));
  }
}

/**
 * Returns the URI used for the given resource.
 */
function restws_resource_uri($resource, $id) {
  // Avoid having the URLs aliased.
  return url($resource . '/' . $id, array('absolute' => TRUE, 'alias' => TRUE));
}

/**
 * Returns an array representing a reference on the given resource. To ease
 * usage, we provide the full URI as well as the resource and its id separately.
 */
function restws_resource_reference($resource, $id) {
  return array(
    'uri' => restws_resource_uri($resource, $id),
    'id' => $id,
    'resource' => $resource,
  );
}

/**
 * Returns the format instance for a given MIME type.
 *
 * @param $mime
 *   The MIME type, e.g. 'application/json' or 'application/xml'.
 *
 * @return
 *   The format controller or FALSE if the format was not found.
 */
function restws_format_mimetype($mime) {
  foreach (restws_get_format_info() as $format_name => $info) {
    if ($info['mime type'] == $mime) {
      return restws_format($format_name);
    }
  }
  return FALSE;
}
