<?php
// $Id$

/**
 * @file
 * Basic authentication login - module file.
 */

/**
 * Implements hook_init().
 *
 * Performs a user login from the credentials in the HTTP Authorization header.
 */
function restws_basic_auth_init() {
  if (isset($_SERVER['PHP_AUTH_USER']) && isset($_SERVER['PHP_AUTH_PW'])) {
    $form_state = array();
    $form_state['values']['name'] = $_SERVER['PHP_AUTH_USER'];
    $form_state['values']['pass'] = $_SERVER['PHP_AUTH_PW'];
    drupal_form_submit('user_login', $form_state);
    drupal_static_reset();
  }
}
